export const GET_CONTACT_REQUESTS = "get_contact_requests";
export const CLOSE_MESSAGE_VIEWER = "CLOSE_MESSAGE_VIEWER";
export const OPEN_MESSAGE = "OPEN_MESSAGE";
export const CONTACT_REQUESTS_FILTER = "CONTACT_REQUESTS_FILTER";
export const CONTACT_REQUESTS_SORT = "CONTACT_REQUESTS_SORT";

export const UPDATE_POST_PROP = "UPDATE_POST_PROP";
export const POST_EDITOR_FETCH_CATEGORIES = "POST_EDITOR_FETCH_CATEGORIES";
export const POST_EDITOR_SUBMIT_SUCCESS = "POST_EDITOR_SUBMIT_SUCCESS";
export const POST_EDITOR_SUBMIT_ERROR = "POST_EDITOR_SUBMIT_ERROR";
export const POST_EDITOR_FETCH_SUCCESS = "POST_EDITOR_FETCH_SUCCESS";
export const POST_EDITOR_SELECT_CATEGORY = "POST_EDITOR_SELECT_CATEGORY";

export const POSTS_FETCH_SUCCESS = "POSTS_FETCH_SUCCESS";
export const POSTS_REMOVE_SUCCESS = "POSTS_REMOVE_SUCCESS";
export const CHANGE_PREVIEW_VISIBILITY = "CHANGE_PREVIEW_VISIBILITY";
export const POSTS_FILTER = "POSTS_FILTER";
export const POSTS_SORT_BY = "POSTS_SORT_BY";

export const CATEGORIES_GET = "CATEGORIES_GET";
export const CATEGORIES_NEW = "CATEGORIES_NEW";
export const CATEGORIES_EDIT = "CATEGORIES_EDIT";
export const CATEGORIES_SAVE = "CATEGORIES_SAVE";
export const CATEGORIES_CANCEL = "CATEGORIES_CANCEL";
export const CATEGORIES_DELETE = "CATEGORIES_DELETE";
export const CATEGORIES_UPDATE = "CATEGORIES_UPDATE";
export const CATEGORIES_TOGGLE_ALERT = "CATEGORIES_TOGGLE_ALERT";
export const CATEGORIES_TAG = "CATEGORIES_TAG";
export const CATEGORIES_DELETE_TAG = "CATEGORIES_DELETE_TAG";
export const CATEGORIES_ADD = "CATEGORIES_ADD";
export const CATEGORIES_FILTER = "CATEGORIES_FILTER";
export const CATEGORIES_GET_ONE = "CATEGORIES_GET_ONE";
export const CATEGORIES_EDIT_SUBCATEGORY = "CATEGORIES_EDIT_SUBCATEGORY";
export const CATEGORIES_EDIT_NAME = "CATEGORIES_EDIT_NAME";
export const CATEGORIES_EDIT_REMOVE = "CATEGORIES_EDIT_REMOVE";
export const CATEGORIES_EDIT_ADD = "CATEGORIES_EDIT_ADD";

export const POSTS_PUBLIC_FETCH = "POSTS_PUBLIC_FETCH";
export const POSTS_PUBLIC_CATEGORIES_GET = "POSTS_PUBLIC_CATEGORIES_GET";
export const POSTS_PUBLIC_FILTER_BY_TEXT = "POSTS_PUBLIC_FILTER_BY_TEXT";
export const POSTS_PUBLIC_FILTER_BY_TAGS = "POSTS_PUBLIC_FILTER_BY_TAGS";
export const POSTS_PUBLIC_FETCH_TAGS = "POSTS_PUBLIC_FETCH_TAGS";
export const POSTS_PUBLIC_SELECT_CATEGORY = "POSTS_PUBLIC_SELECT_CATEGORY";
export const POSTS_PUBLIC_UNSELECT_CATEGORY = "POSTS_PUBLIC_UNSELECT_CATEGORY";
export const POSTS_PUBLIC_SELECT_SUBCATEGORY =
  "POSTS_PUBLIC_SELECT_SUBCATEGORY";
export const POSTS_PUBLIC_GO_BACK = "POSTS_PUBLIC_GO_BACK";
export const POSTS_PUBLIC_TOGGLE_CATEGORIES = "POSTS_PUBLIC_TOGGLE_CATEGORIES";

export const ABOUT_UPDATE = "ABOUT_UPDATE";
export const ABOUT_GET = "ABOUT_GET";
export const ABOUT_SAVE = "ABOUT_SAVE";
export const ABOUT_CLEAR_PHOTO = "ABOUT_CLEAR_PHOTO";
export const ABOUT_EDIT = "ABOUT_EDIT";

export const AUTHOR_UPDATE = "AUTHOR_UPDATE";
export const AUTHOR_GET = "AUTHOR_GET";
export const AUTHOR_GET_BY_ID = "AUTHOR_GET_BY_ID";
export const AUTHOR_SAVE = "AUTHOR_SAVE";
export const AUTHOR_CLEAR_PHOTO = "AUTHOR_CLEAR_PHOTO";
export const AUTHOR_DELETE = "AUTHOR_DELETE";
export const AUTHOR_SHOW = "AUTHOR_SHOW";
export const AUTHOR_HIDE = "AUTHOR_HIDE";
export const AUTHOR_SET_IMAGE = "AUTHOR_SET_IMAGE";
