export const GET_CONTACT_REQUESTS = "get_contact_requests";
export const CLOSE_MESSAGE_VIEWER = "CLOSE_MESSAGE_VIEWER";
export const OPEN_MESSAGE = "OPEN_MESSAGE";
export const CONTACT_REQUESTS_FILTER = "CONTACT_REQUESTS_FILTER";
export const CONTACT_REQUESTS_SORT = "CONTACT_REQUESTS_SORT";

export const UPDATE_POST_PROP = "UPDATE_POST_PROP";
export const POST_EDITOR_FETCH_CATEGORIES = "POST_EDITOR_FETCH_CATEGORIES";
export const POST_EDITOR_SUBMIT_SUCCESS = "POST_EDITOR_SUBMIT_SUCCESS";
export const POST_EDITOR_SUBMIT_ERROR = "POST_EDITOR_SUBMIT_ERROR";
export const POST_EDITOR_FETCH_SUCCESS = "POST_EDITOR_FETCH_SUCCESS";

export const POSTS_FETCH_SUCCESS = "POSTS_FETCH_SUCCESS";
export const POSTS_REMOVE_SUCCESS = "POSTS_REMOVE_SUCCESS";
export const CHANGE_PREVIEW_VISIBILITY = "CHANGE_PREVIEW_VISIBILITY";
export const POSTS_FILTER = "POSTS_FILTER";
export const POSTS_SORT_BY = "POSTS_SORT_BY";

export const CATEGORIES_GET = "CATEGORIES_GET";
