apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quantum
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: quantum
    spec:
      containers:
        - env:
          - name: PORT
            value: "8080"
        name: quantum
        image: radu/quantum:v3
        ports:
        - name: nodejs-port
          containerPort: 80