apiVersion: v1
kind: Service
metadata:
  name: quantum
  labels:
    app: quantum
spec:
  selector:
    app: quantum
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
  
